version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_senai  
    container_name: senai_desi  
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1