# Generated by Django 5.1 on 2024-10-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_equipamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'permissions': [('deletar_colaboradores', 'Pode deletar colaboradores'), ('editar_colaboradores', 'Pode editar colaboradores'), ('criar_colaboradores', 'Pode criar colaboradores')]},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'permissions': [('deletar_emprestimos', 'Pode deletar empréstimos'), ('editar_emprestimos', 'Pode editar empréstimos'), ('criar_emprestimos', 'Pode criar empréstimos')]},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'permissions': [('deletar_equipamentos', 'Pode deletar equipamentos'), ('editar_equipamentos', 'Pode editar equipamentos'), ('criar_equipamentos', 'Pode criar equipamentos')]},
        ),
    ]
