# Generated by Django 5.1 on 2024-09-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_equipamento',
            field=models.IntegerField(null=True),
        ),
    ]
