# Generated by Django 5.1 on 2024-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_colaborador_options_alter_emprestimo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(null=True),
        ),
    ]
